root: true
env:
    browser: true
    es2022: true
parserOptions:
    ecmaVersion: 13
plugins:
    - eslint-plugin-vue
extends:
    - eslint:recommended
    - plugin:vue/vue3-recommended
    - eslint-config-prettier
rules:
    {
        vue/comment-directive: 0,
        vue/jsx-uses-vars: 0,
        vue/require-default-prop: 0,
        vue/multi-word-component-names: [2, { 'ignores': ['index'] }],
    }
