root: true
env:
  browser: true
  es2022: true
parserOptions:
  ecmaVersion: 13
plugins:
  - eslint-plugin-vue
extends:
  - eslint:recommended
  - "plugin:vue/vue3-recommended"
rules: {
  vue/require-default-prop: 0
}
