root: true
env:
    browser: true
    es2022: true
parserOptions:
    ecmaVersion: 13
plugins:
    - eslint-plugin-vue
extends:
    - eslint:recommended
    - plugin:vue/base
    - eslint-config-prettier
rules:
    {
        vue/comment-directive: 0,
        vue/jsx-uses-vars: 0,
        vue/require-default-prop: 0,
    }
